Repository wecode-bootcamp-korea/15-1st-MarketBully-frontend, pull requests merged in 2020-12, with the labels that each got.

#2 [15기 박채훈] ItemCard 컴포넌트 완성 / git 리뷰사항 적용 완료
  public/images/image
  src/Components/AsideMenu/AsideMenu.js
  src/Components/Header/Header.js
  src/Components/ItemCard/ItemCard.js
  src/Components/ItemCard/ItemCard.scss
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 요청

#7 [15기 이장현] 리덕스 삭제 및 Conflict 해결
  package-lock.json
  package.json
  public/images/marketbully.png
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
Labels: Status: Accepted

#4 [15기 이장현] 상세 페이지(ItemDetail) 컴포넌트 분리 및 전체 레이아웃 완료. 기능 구현 중.
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/images/tomato.jpg
  src/Pages/ItemDetail/Components/Board.js
  src/Pages/ItemDetail/Components/Board.scss
  src/Pages/ItemDetail/Components/CustomerReview.js
  src/Pages/ItemDetail/Components/CustomerReview.scss
  src/Pages/ItemDetail/Components/DetailInfo.js
  src/Pages/ItemDetail/Components/DetailInfo.scss
  src/Pages/ItemDetail/Components/InfoAndCartPut.js
  src/Pages/ItemDetail/Components/InfoAndCartPut.scss
  src/Pages/ItemDetail/Components/ItemDescription.js
  src/Pages/ItemDetail/Components/ItemDescription.scss
  src/Pages/ItemDetail/Components/ItemDetailMenu.js
  src/Pages/ItemDetail/Components/ItemDetailMenu.scss
  src/Pages/ItemDetail/Components/ItemImage.js
  src/Pages/ItemDetail/Components/ItemImage.scss
  src/Pages/ItemDetail/Components/ItemInquire.js
  src/Pages/ItemDetail/Components/ItemInquire.scss
  src/Pages/ItemDetail/Components/RelatedProduct.js
  src/Pages/ItemDetail/Components/RelatedProduct.scss
  src/Pages/ItemDetail/ItemDetail.js
  src/Pages/ItemDetail/ItemDetail.scss
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 리뷰 요청

#3 [15기 한민아]로그인페이지 기능구현중
  package-lock.json
  package.json
  public/images/checked.png
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Styles/reset.scss
Labels: Status: 추가 기능 구현중

#11 [15기 이장현] 제품 상세(ItemDetail 컴포넌트) 페이지 완료.
  public/data/inquire.json
  public/data/itemdata.json
  public/data/itemdetail.json
  public/data/review.json
  public/images/WHYBULLY.png
  src/Components/AsideMenu/AsideMenu.js
  src/Components/AsideMenu/AsideMenu.scss
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Pages/ItemDetail/Components/Board.js
  src/Pages/ItemDetail/Components/Board.scss
  src/Pages/ItemDetail/Components/CustomerReview.js
  src/Pages/ItemDetail/Components/DetailInfo.js
  src/Pages/ItemDetail/Components/DetailInfo.scss
  src/Pages/ItemDetail/Components/InfoAndCartPut.js
  src/Pages/ItemDetail/Components/InfoAndCartPut.scss
  src/Pages/ItemDetail/Components/ItemDescription.js
  src/Pages/ItemDetail/Components/ItemDescription.scss
  src/Pages/ItemDetail/Components/ItemDetailMenu.scss
  src/Pages/ItemDetail/Components/ItemImage.js
  src/Pages/ItemDetail/Components/ItemImage.scss
  src/Pages/ItemDetail/Components/ItemInquire.js
  src/Pages/ItemDetail/Components/RelatedProduct.js
  src/Pages/ItemDetail/Components/RelatedProduct.scss
  src/Pages/ItemDetail/ItemDetail.js
  src/Pages/ItemDetail/ItemDetail.scss
  src/Pages/NotFound/NotFound.js
  src/Pages/NotFound/NotFound.scss
  src/Routes.js
  src/Styles/reset.scss
Labels: Status: Accepted

#10 [15기 이장현] 장바구니(ItemCart 컴포넌트 완료. 결제(Payment 컴포넌트) 완료. 충돌 해결 완료
  public/data/cartdata.json
  public/data/cartrealdata.json
  public/images/cancel.svg
  public/images/cold.svg
  public/images/frozen.svg
  public/images/room.svg
  public/images/tomato2.jpg
  public/index.html
  src/Components/AsideMenu/AsideMenu.scss
  src/Pages/ItemCart/Components/CartItemCard.js
  src/Pages/ItemCart/Components/CartTitleCard.js
  src/Pages/ItemCart/ItemCart.js
  src/Pages/ItemCart/ItemCart.scss
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/config.js
  src/utils.js
Labels: Status: 리뷰 요청

#5 [15기 박채훈] ItemCard 리팩토링( 삼항연산자&Short Circuit 간소화 )
  public/data/item.json
  public/images/park.jpg
  public/images/samsamsam.jpeg
  public/index.html
  src/Components/ItemCard/ItemCard.js
  src/Components/ItemCard/ItemCard.scss
  src/Pages/ItemList/ItemList.js
  src/Pages/ItemList/ItemList.scss
  src/Pages/ItemList/ItemListModal.js
  src/Pages/ItemList/ItemListModal.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: Accepted

#1 [15기 김찬영] Header 컨플리트해결완료! 머지요청!
  .gitignore
  debug.log
  package.json
  public/images/marketbully.jpg
  src/Components/Header/First.js
  src/Components/Header/Header.css
  src/Components/Header/Header.css.map
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/LoginHeader.js
  src/Components/Header/LoginHeader.scss
  src/Components/Header/NotLoginHeader.js
  src/Components/Header/NotLoginHeader.scss
  src/Components/Header/Second.js
  src/Components/Header/Third.js
  src/Pages/Home/Home.js
  src/Styles/common.css
  src/Styles/common.css.map
  src/Styles/reset.css
  src/Styles/reset.css.map
  yarn.lock
Labels: Status: 수정 요청

#9 [15기 한민아]회원가입페이지 완료
  .vscode/settings.json
  package-lock.json
  package.json
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 리뷰 요청

#14 [15기 한민아] 로그인페이지 완성
  package-lock.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
Labels: Status: 리뷰 진행중

#6 [15기] 김찬영 Main 컨플리트해결완료 머지요청
  public/data/data.json
  public/data/filterName.json
  public/images/111.jpg
  public/images/new.png
  public/images/감자.png
  public/images/디저트.jpg
  public/images/디저트1.jpg
  public/images/밥상.jpg
  public/images/스윗파이.png
  public/images/스테이크.jpg
  public/images/스파케티.jpg
  public/images/시카고햄버거.png
  public/images/야채.png
  public/images/초록색.png
  public/images/크리스마스.png
  public/images/포도.png
  public/images/하이.png
  public/images/햄버거.png
  src/Pages/Home/BannerMain.js
  src/Pages/Home/EventNews.js
  src/Pages/Home/Home.js
  src/Pages/Home/MDRecommand.js
  src/Pages/Home/MDRecommand/FirstMDRecommand.js
  src/Pages/Home/MDRecommand/FiveMDRecommand.js
  src/Pages/Home/MDRecommand/FourMDRecommand.js
  src/Pages/Home/MDRecommand/InitialMDRecomman.js
  src/Pages/Home/MDRecommand/SecondMDRecommand.js
  src/Pages/Home/MDRecommand/SixMDRecommand.js
  src/Pages/Home/MDRecommand/ThirdMDRecommand.js
  src/Pages/Home/RecommandGoods.js
  src/Pages/Home/Slide/BannerSlide.js
  src/Pages/Home/Slide/RecommandSlide.js
  src/Pages/Home/YearEndSpecial.js
  src/Pages/Home/config/BannerMain.scss
  src/Pages/Home/config/BannerSlide.scss
  src/Pages/Home/config/EventNews.scss
  src/Pages/Home/config/MDRcommandSlide.scss
  src/Pages/Home/config/RecommandSlide.scss
  src/Pages/Home/config/YearEndSpecial.scss
  yarn.lock
Labels: Status: 리뷰 요청

#17 [15기 한민아]회원가입페이지 완성
  src/Pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#18 [15기 한민아]ADD: 회원가입페이지로 이동 링크연결
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
Labels: Status: 리뷰 요청

#19 Feature/header 추가기능 구현완료
  debug.log
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/LoginHeader.js
  src/Components/Header/NavBar.js
  src/Components/Header/NavBar.scss
  src/Components/Header/NotLoginHeader.scss
Labels: Status: 리뷰 요청

#13 [15기 이장현] 전체적인 코드 리팩토링. 게시판 pagination 기능 구현.
  public/data/cartdata.json
  public/data/data.json
  public/data/inquire.json
  public/data/itemdetail.json
  public/data/review.json
  src/Components/AsideMenu/AsideMenu.js
  src/Components/AsideMenu/AsideMenu.scss
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/Header/LoginHeader.js
  src/Components/Header/NavBar.scss
  src/Components/Header/NotLoginHeader.js
  src/Components/Header/Second.js
  src/Components/Header/Third.js
  src/Components/ItemCard/ItemCard.js
  src/Components/ItemCard/ItemCard.scss
  src/Pages/Home/BannerMain.js
  src/Pages/Home/EventNews.js
  src/Pages/Home/Slide/BannerSlide.js
  src/Pages/Home/Slide/RecommandSlide.js
  src/Pages/Home/YearEndSpecial.js
  src/Pages/ItemCart/Components/CartItemCard.js
  src/Pages/ItemCart/Components/CartTitleCard.js
  src/Pages/ItemCart/ItemCart.js
  src/Pages/ItemCart/ItemCart.scss
  src/Pages/ItemDetail/Components/Board.js
  src/Pages/ItemDetail/Components/CustomerReview.js
  src/Pages/ItemDetail/Components/CustomerReview.scss
  src/Pages/ItemDetail/Components/DetailInfo.js
  src/Pages/ItemDetail/Components/InfoAndCartPut.js
  src/Pages/ItemDetail/Components/ItemDescription.js
  src/Pages/ItemDetail/Components/ItemDetailMenu.js
  src/Pages/ItemDetail/Components/ItemImage.js
  src/Pages/ItemDetail/Components/ItemInquire.js
  src/Pages/ItemDetail/Components/ItemInquire.scss
  src/Pages/ItemDetail/Components/RelatedProduct.js
  src/Pages/ItemDetail/Components/Style/Board.scss
  src/Pages/ItemDetail/Components/Style/DetailInfo.scss
  src/Pages/ItemDetail/Components/Style/InfoAndCartPut.scss
  src/Pages/ItemDetail/Components/Style/ItemDescription.scss
  src/Pages/ItemDetail/Components/Style/ItemDetailMenu.scss
  src/Pages/ItemDetail/Components/Style/ItemImage.scss
  src/Pages/ItemDetail/Components/Style/RelatedProduct.scss
  src/Pages/ItemDetail/ItemDetail.js
  src/Pages/ItemList/ItemList.scss
  src/Pages/Login/Login.js
  src/Pages/Payment/Payment.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
  src/utils.js
Labels: Status: 리뷰 요청
